const DoublyLinkedList = require('./src/Lists/DoublyLinkedList')
const SinglyLinkedList = require('./src/Lists/SinglyLinkedList')
const li = new DoublyLinkedList()
//const li = new SinglyLinkedList()

li.print()
li.insertAtHead(10)
li.insertAtHead(20)
li.insertAtHead(30)
li.insertAtHead(40)
li.insertAtHead(50)
li.insertAtHead(60)
li.print()
